In [2]:
# importing the module
import pandas as pd
data=pd.read_csv("Mobile_Specification_data.csv")
data

,Unnamed: 0,Name,Brand,Model,Battery capacity (mAh),Screen size (inches),Touchscreen,Resolution x,Resolution y,Processor,...,Rear camera,Front camera,Operating system,Wi-Fi,Bluetooth,GPS,Number of SIMs,3G,4G/ LTE,Price
0,0,OnePlus 7T Pro McLaren Edition,OnePlus,7T Pro McLaren Edition,4085,6.67,Yes,1440,3120,8,...,48.0,16.0,Android,Yes,Yes,Yes,2,Yes,Yes,58998
1,1,Realme X2 Pro,Realme,X2 Pro,4000,6.50,Yes,1080,2400,8,...,64.0,16.0,Android,Yes,Yes,Yes,2,Yes,Yes,27999
2,2,iPhone 11 Pro Max,Apple,iPhone 11 Pro Max,3969,6.50,Yes,1242,2688,6,...,12.0,12.0,iOS,Yes,Yes,Yes,2,Yes,Yes,106900
3,3,iPhone 11,Apple,iPhone 11,3110,6.10,Yes,828,1792,6,...,12.0,12.0,iOS,Yes,Yes,Yes,2,Yes,Yes,62900
4,4,LG G8X ThinQ,LG,G8X ThinQ,4000,6.40,Yes,1080,2340,8,...,12.0,32.0,Android,Yes,Yes,Yes,1,No,No,49990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1354,1354,Intex Aqua A2,Intex,Aqua A2,1500,4.00,Yes,480,800,4,...,5.0,0.3,Android,Yes,Yes,Yes,2,Yes,No,2599
1355,1355,Videocon Infinium Z51 Nova+,Videocon,Infinium Z51 Nova+,2000,5.00,Yes,480,854,4,...,8.0,5.0,Android,Yes,Yes,Yes,2,Yes,No,2940
1356,1356,Intex Aqua Y4,Intex,Aqua Y4,1700,4.50,Yes,480,854,2,...,5.0,2.0,Android,Yes,Yes,No,2,Yes,No,2999
1357,1357,iBall Andi4 B20,iBall,Andi4 B20,1250,4.00,Yes,480,800,1,...,2.0,0.3,Android,Yes,Yes,Yes,2,Yes,No,2498
1358,1358,iBall Andi Avonte 5,iBall,Andi Avonte 5,2150,5.00,Yes,480,854,4,...,8.0,0.0,Android,Yes,Yes,Yes,2,Yes,No,3999

In [11]:
upd_data=data[(data["Brand"]=="Apple")
      |(data["Brand"]=="Samsung")
      |(data["Brand"]=="OnePlus")
      |(data["Brand"]=="Realme")
      |(data["Brand"]=="Infinix")
      |(data["Brand"]=="Techno")
      |(data["Brand"]=="Oppo")
      |(data["Brand"]=="Vivo")
      |(data["Brand"]=="Xiaomi")
      |(data["Brand"]=="Nokia")]

upd_data

,Unnamed: 0,Name,Brand,Model,Battery capacity (mAh),Screen size (inches),Touchscreen,Resolution x,Resolution y,Processor,...,Rear camera,Front camera,Operating system,Wi-Fi,Bluetooth,GPS,Number of SIMs,3G,4G/ LTE,Price
0,0,OnePlus 7T Pro McLaren Edition,OnePlus,7T Pro McLaren Edition,4085,6.67,Yes,1440,3120,8,...,48.0,16.0,Android,Yes,Yes,Yes,2,Yes,Yes,58998
1,1,Realme X2 Pro,Realme,X2 Pro,4000,6.50,Yes,1080,2400,8,...,64.0,16.0,Android,Yes,Yes,Yes,2,Yes,Yes,27999
2,2,iPhone 11 Pro Max,Apple,iPhone 11 Pro Max,3969,6.50,Yes,1242,2688,6,...,12.0,12.0,iOS,Yes,Yes,Yes,2,Yes,Yes,106900
3,3,iPhone 11,Apple,iPhone 11,3110,6.10,Yes,828,1792,6,...,12.0,12.0,iOS,Yes,Yes,Yes,2,Yes,Yes,62900
5,5,OnePlus 7T,OnePlus,7T,3800,6.55,Yes,1080,2400,8,...,48.0,16.0,Android,Yes,Yes,No,2,Yes,Yes,34930
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1282,1282,Samsung Z3,Samsung,Z3,2600,5.00,Yes,720,1280,4,...,8.0,5.0,Tizen,Yes,Yes,Yes,2,Yes,No,4990
1294,1294,Vivo Y15S,Vivo,Y15S,1900,4.50,Yes,854,480,4,...,5.0,2.0,Android,Yes,Yes,Yes,2,Yes,No,4999
1295,1295,Samsung Galaxy J1 Ace,Samsung,Galaxy J1 Ace,1800,4.30,Yes,480,800,2,...,5.0,2.0,Android,Yes,Yes,Yes,2,Yes,No,4300
1296,1296,Vivo Y27L,Vivo,Y27L,2260,4.70,Yes,720,1280,4,...,8.0,5.0,Android,Yes,Yes,Yes,2,Yes,Yes,9001
1350,1350,Vivo V1,Vivo,V1,2300,5.00,Yes,720,1280,4,...,13.0,5.0,Android,Yes,Yes,Yes,2,Yes,Yes,15300

In [7]:
data.head()

,Unnamed: 0,Name,Brand,Model,Battery capacity (mAh),Screen size (inches),Touchscreen,Resolution x,Resolution y,Processor,...,Rear camera,Front camera,Operating system,Wi-Fi,Bluetooth,GPS,Number of SIMs,3G,4G/ LTE,Price
0,0,OnePlus 7T Pro McLaren Edition,OnePlus,7T Pro McLaren Edition,4085,6.67,Yes,1440,3120,8,...,48.0,16.0,Android,Yes,Yes,Yes,2,Yes,Yes,58998
1,1,Realme X2 Pro,Realme,X2 Pro,4000,6.50,Yes,1080,2400,8,...,64.0,16.0,Android,Yes,Yes,Yes,2,Yes,Yes,27999
2,2,iPhone 11 Pro Max,Apple,iPhone 11 Pro Max,3969,6.50,Yes,1242,2688,6,...,12.0,12.0,iOS,Yes,Yes,Yes,2,Yes,Yes,106900
3,3,iPhone 11,Apple,iPhone 11,3110,6.10,Yes,828,1792,6,...,12.0,12.0,iOS,Yes,Yes,Yes,2,Yes,Yes,62900
4,4,LG G8X ThinQ,LG,G8X ThinQ,4000,6.40,Yes,1080,2340,8,...,12.0,32.0,Android,Yes,Yes,Yes,1,No,No,49990

In [9]:
data.tail()

,Unnamed: 0,Name,Brand,Model,Battery capacity (mAh),Screen size (inches),Touchscreen,Resolution x,Resolution y,Processor,...,Rear camera,Front camera,Operating system,Wi-Fi,Bluetooth,GPS,Number of SIMs,3G,4G/ LTE,Price
1354,1354,Intex Aqua A2,Intex,Aqua A2,1500,4.0,Yes,480,800,4,...,5.0,0.3,Android,Yes,Yes,Yes,2,Yes,No,2599
1355,1355,Videocon Infinium Z51 Nova+,Videocon,Infinium Z51 Nova+,2000,5.0,Yes,480,854,4,...,8.0,5.0,Android,Yes,Yes,Yes,2,Yes,No,2940
1356,1356,Intex Aqua Y4,Intex,Aqua Y4,1700,4.5,Yes,480,854,2,...,5.0,2.0,Android,Yes,Yes,No,2,Yes,No,2999
1357,1357,iBall Andi4 B20,iBall,Andi4 B20,1250,4.0,Yes,480,800,1,...,2.0,0.3,Android,Yes,Yes,Yes,2,Yes,No,2498
1358,1358,iBall Andi Avonte 5,iBall,Andi Avonte 5,2150,5.0,Yes,480,854,4,...,8.0,0.0,Android,Yes,Yes,Yes,2,Yes,No,3999

In [12]:
data.sample()

,Unnamed: 0,Name,Brand,Model,Battery capacity (mAh),Screen size (inches),Touchscreen,Resolution x,Resolution y,Processor,...,Rear camera,Front camera,Operating system,Wi-Fi,Bluetooth,GPS,Number of SIMs,3G,4G/ LTE,Price
1308,1308,Lenovo Vibe P1m,Lenovo,Vibe P1m,3900,5.0,Yes,720,1280,4,...,8.0,5.0,Android,Yes,Yes,Yes,2,Yes,Yes,6999

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1359 entries, 0 to 1358
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              1359 non-null   int64
 1   Name                    1359 non-null   object
 2   Brand                   1359 non-null   object
 3   Model                   1359 non-null   object
 4   Battery capacity (mAh)  1359 non-null   int64
 5   Screen size (inches)    1359 non-null   float64
 6   Touchscreen             1359 non-null   object
 7   Resolution x            1359 non-null   int64
 8   Resolution y            1359 non-null   int64
 9   Processor               1359 non-null   int64
 10  RAM (MB)                1359 non-null   int64
 11  Internal storage (GB)   1359 non-null   float64
 12  Rear camera             1359 non-null   float64
 13  Front camera            1359 non-null   float64
 14  Operating system        1359 non-null   object
 15  Wi-Fi                   1359 non-null   object
 16  Bluetooth               1359 non-null   object
 17  GPS                     1359 non-null   object
 18  Number of SIMs          1359 non-null   int64
 19  3G                      1359 non-null   object
 20  4G/ LTE                 1359 non-null   object
 21  Price                   1359 non-null   int64
dtypes: float64(4), int64(8), object(10)
memory usage: 233.7+ KB

In [18]:
data.size

29898

In [21]:
data.shape

(1359, 22)

In [23]:
data.isnull()

,Unnamed: 0,Name,Brand,Model,Battery capacity (mAh),Screen size (inches),Touchscreen,Resolution x,Resolution y,Processor,...,Rear camera,Front camera,Operating system,Wi-Fi,Bluetooth,GPS,Number of SIMs,3G,4G/ LTE,Price
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1354,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1355,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1356,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1357,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1358,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [25]:
data.isnull().sum()

Unnamed: 0                0
Name                      0
Brand                     0
Model                     0
Battery capacity (mAh)    0
Screen size (inches)      0
Touchscreen               0
Resolution x              0
Resolution y              0
Processor                 0
RAM (MB)                  0
Internal storage (GB)     0
Rear camera               0
Front camera              0
Operating system          0
Wi-Fi                     0
Bluetooth                 0
GPS                       0
Number of SIMs            0
3G                        0
4G/ LTE                   0
Price                     0
dtype: int64

In [26]:
# 5. How does the data look mathematically?
data.describe()# mathematically summary of data

,Unnamed: 0,Battery capacity (mAh),Screen size (inches),Resolution x,Resolution y,Processor,RAM (MB),Internal storage (GB),Rear camera,Front camera,Number of SIMs,Price
count,1359.000000,1359.000000,1359.000000,1359.000000,1359.000000,1359.000000,1359.000000,1359.000000,1359.000000,1359.000000,1359.000000,1359.000000
mean,679.000000,2938.489330,5.291310,811.543046,1490.777778,5.551141,2488.777778,30.654864,12.070199,7.037969,1.833701,11465.825607
std,392.453819,873.514133,0.671357,270.707271,557.780120,2.196562,1664.440386,36.950241,8.948337,6.295448,0.374457,13857.497077
min,0.000000,1010.000000,2.400000,240.000000,320.000000,1.000000,64.000000,0.064000,0.000000,0.000000,1.000000,494.000000
25%,339.500000,2300.000000,5.000000,720.000000,1280.000000,4.000000,1000.000000,8.000000,8.000000,2.000000,2.000000,4763.500000
50%,679.000000,3000.000000,5.200000,720.000000,1280.000000,4.000000,2000.000000,16.000000,12.200000,5.000000,2.000000,6999.000000
75%,1018.500000,3500.000000,5.700000,1080.000000,1920.000000,8.000000,3000.000000,32.000000,13.000000,8.000000,2.000000,11999.000000
max,1358.000000,6000.000000,7.300000,2160.000000,3840.000000,10.000000,12000.000000,512.000000,108.000000,48.000000,3.000000,174990.000000

In [27]:
# 6. Are there duplicate values?
data.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1354    False
1355    False
1356    False
1357    False
1358    False
Length: 1359, dtype: bool

In [28]:
data.duplicated().sum()

0

In [30]:
# 7. How is the correlation between cols?
data.corr

<bound method DataFrame.corr of       Unnamed: 0                            Name     Brand  \
0              0  OnePlus 7T Pro McLaren Edition   OnePlus
1              1                   Realme X2 Pro    Realme
2              2               iPhone 11 Pro Max     Apple
3              3                       iPhone 11     Apple
4              4                    LG G8X ThinQ        LG
...          ...                             ...       ...
1354        1354                   Intex Aqua A2     Intex
1355        1355     Videocon Infinium Z51 Nova+  Videocon
1356        1356                   Intex Aqua Y4     Intex
1357        1357                 iBall Andi4 B20     iBall
1358        1358             iBall Andi Avonte 5     iBall

                       Model  Battery capacity (mAh)  Screen size (inches)  \
0     7T Pro McLaren Edition                    4085                  6.67
1                     X2 Pro                    4000                  6.50
2          iPhone 11 Pro Max                    3969                  6.50
3                  iPhone 11                    3110                  6.10
4                  G8X ThinQ                    4000                  6.40
...                      ...                     ...                   ...
1354                 Aqua A2                    1500                  4.00
1355      Infinium Z51 Nova+                    2000                  5.00
1356                 Aqua Y4                    1700                  4.50
1357               Andi4 B20                    1250                  4.00
1358           Andi Avonte 5                    2150                  5.00

     Touchscreen  Resolution x  Resolution y  Processor  ...  Rear camera  \
0            Yes          1440          3120          8  ...         48.0
1            Yes          1080          2400          8  ...         64.0
2            Yes          1242          2688          6  ...         12.0
3            Yes           828          1792          6  ...         12.0
4            Yes          1080          2340          8  ...         12.0
...          ...           ...           ...        ...  ...          ...
1354         Yes           480           800          4  ...          5.0
1355         Yes           480           854          4  ...          8.0
1356         Yes           480           854          2  ...          5.0
1357         Yes           480           800          1  ...          2.0
1358         Yes           480           854          4  ...          8.0

      Front camera  Operating system  Wi-Fi Bluetooth  GPS Number of SIMs  \
0             16.0           Android    Yes       Yes  Yes              2
1             16.0           Android    Yes       Yes  Yes              2
2             12.0               iOS    Yes       Yes  Yes              2
3             12.0               iOS    Yes       Yes  Yes              2
4             32.0           Android    Yes       Yes  Yes              1
...            ...               ...    ...       ...  ...            ...
1354           0.3           Android    Yes       Yes  Yes              2
1355           5.0           Android    Yes       Yes  Yes              2
1356           2.0           Android    Yes       Yes   No              2
1357           0.3           Android    Yes       Yes  Yes              2
1358           0.0           Android    Yes       Yes  Yes              2

       3G  4G/ LTE   Price
0     Yes      Yes   58998
1     Yes      Yes   27999
2     Yes      Yes  106900
3     Yes      Yes   62900
4      No       No   49990
...   ...      ...     ...
1354  Yes       No    2599
1355  Yes       No    2940
1356  Yes       No    2999
1357  Yes       No    2498
1358  Yes       No    3999

[1359 rows x 22 columns]>

In [31]:
data.mode()

,Unnamed: 0,Name,Brand,Model,Battery capacity (mAh),Screen size (inches),Touchscreen,Resolution x,Resolution y,Processor,...,Rear camera,Front camera,Operating system,Wi-Fi,Bluetooth,GPS,Number of SIMs,3G,4G/ LTE,Price
0,0,10.or D,Intex,V5,3000.0,5.0,Yes,720.0,1280.0,4.0,...,13.0,5.0,Android,Yes,Yes,Yes,2.0,Yes,Yes,4999.0
1,1,10.or D2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,10.or E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,10.or G,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,10.or G2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1354,1354,iVoomi i2 Lite,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1355,1355,iVoomi iPro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1356,1356,iVoomi iV505,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1357,1357,mPhone 7 Plus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1358,1358,mPhone 8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
data.corr(numeric_only=True)

,Unnamed: 0,Battery capacity (mAh),Screen size (inches),Resolution x,Resolution y,Processor,RAM (MB),Internal storage (GB),Rear camera,Front camera,Number of SIMs,Price
Unnamed: 0,1.000000,-0.417557,-0.448372,-0.465304,-0.546045,-0.424670,-0.502721,-0.444736,-0.424549,-0.443835,0.097866,-0.359745
Battery capacity (mAh),-0.417557,1.000000,0.746886,0.495362,0.573969,0.538017,0.600969,0.483489,0.499756,0.540250,0.040151,0.297525
Screen size (inches),-0.448372,0.746886,1.000000,0.590146,0.709646,0.631984,0.707088,0.612804,0.581909,0.651781,0.037657,0.402462
Resolution x,-0.465304,0.495362,0.590146,1.000000,0.920780,0.583203,0.687661,0.544791,0.506104,0.467119,-0.171891,0.540711
Resolution y,-0.546045,0.573969,0.709646,0.920780,1.000000,0.642540,0.771964,0.640653,0.600198,0.585385,-0.134961,0.576152
Processor,-0.424670,0.538017,0.631984,0.583203,0.642540,1.000000,0.615097,0.481688,0.468668,0.556287,0.039891,0.302492
RAM (MB),-0.502721,0.600969,0.707088,0.687661,0.771964,0.615097,1.000000,0.847864,0.661602,0.696881,-0.023896,0.613446
Internal storage (GB),-0.444736,0.483489,0.612804,0.544791,0.640653,0.481688,0.847864,1.000000,0.572591,0.613574,-0.015116,0.644079
Rear camera,-0.424549,0.499756,0.581909,0.506104,0.600198,0.468668,0.661602,0.572591,1.000000,0.639652,-0.038466,0.379120
Front camera,-0.443835,0.540250,0.651781,0.467119,0.585385,0.556287,0.696881,0.613574,0.639652,1.000000,0.054066,0.310672
Number of SIMs,0.097866,0.040151,0.037657,-0.171891,-0.134961,0.039891,-0.023896,-0.015116,-0.038466,0.054066,1.000000,-0.162491
Price,-0.359745,0.297525,0.402462,0.540711,0.576152,0.302492,0.613446,0.644079,0.379120,0.310672,-0.162491,1.000000

In [51]:
data.columns

Index(['Unnamed: 0', 'Name', 'Brand', 'Model', 'Battery capacity (mAh)',
       'Screen size (inches)', 'Touchscreen', 'Resolution x', 'Resolution y',
       'Processor', 'RAM (MB)', 'Internal storage (GB)', 'Rear camera',
       'Front camera', 'Operating system', 'Wi-Fi', 'Bluetooth', 'GPS',
       'Number of SIMs', '3G', '4G/ LTE', 'Price'],
      dtype='object')

# WORKING ON COLUMNS = "Battery capacity (mAh)","Screen size (inches)","Touchscreen"

In [33]:
selected_columns = ["Battery capacity (mAh)","Screen size (inches)","Touchscreen"]
selected_data = data[selected_columns]
print(selected_data.describe())

       Battery capacity (mAh)  Screen size (inches)
count             1359.000000           1359.000000
mean              2938.489330              5.291310
std                873.514133              0.671357
min               1010.000000              2.400000
25%               2300.000000              5.000000
50%               3000.000000              5.200000
75%               3500.000000              5.700000
max               6000.000000              7.300000

In [35]:

import pandas as pd
selected_columns = ["Battery capacity (mAh)","Screen size (inches)","Touchscreen"]
selected_data = data[selected_columns]
print(selected_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1359 entries, 0 to 1358
Data columns (total 3 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Battery capacity (mAh)  1359 non-null   int64
 1   Screen size (inches)    1359 non-null   float64
 2   Touchscreen             1359 non-null   object
dtypes: float64(1), int64(1), object(1)
memory usage: 32.0+ KB
None

In [36]:
import pandas as pd
selected_columns = ["Battery capacity (mAh)","Screen size (inches)","Touchscreen"]
selected_data= data[selected_columns]
print(selected_data.nunique())

Battery capacity (mAh)    165
Screen size (inches)       80
Touchscreen                 2
dtype: int64

In [38]:
data["Battery capacity (mAh)"].value_counts()

Battery capacity (mAh)
3000    182
4000    145
2000    115
2500     91
5000     49
       ...
3250      1
3550      1
3730      1
5100      1
1960      1
Name: count, Length: 165, dtype: int64

In [39]:
data["Screen size (inches)"].value_counts()

Screen size (inches)
5.00    404
5.50    251
5.20     82
4.50     80
4.00     71
       ...
2.40      1
6.01      1
6.23      1
6.42      1
7.00      1
Name: count, Length: 80, dtype: int64

In [40]:
data["Touchscreen"].value_counts()

Touchscreen
Yes    1342
No       17
Name: count, dtype: int64

In [42]:
selected_columns = ["Battery capacity (mAh)","Screen size (inches)","Touchscreen"]
min_values = data[["Battery capacity (mAh)","Screen size (inches)","Touchscreen"]].min()
print("Min values:")
print(min_values)

Min values:
Battery capacity (mAh)    1010
Screen size (inches)       2.4
Touchscreen                 No
dtype: object

In [43]:
max_values = data[["Battery capacity (mAh)","Screen size (inches)","Touchscreen"]].max()
print("Maximum values:")
print(max_values)

Maximum values:
Battery capacity (mAh)    6000
Screen size (inches)       7.3
Touchscreen                Yes
dtype: object

In [45]:
data.describe = data[["Screen size (inches)","Touchscreen"]].describe()

print("describe")
print(data.describe)

describe
       Screen size (inches)
count           1359.000000
mean               5.291310
std                0.671357
min                2.400000
25%                5.000000
50%                5.200000
75%                5.700000
max                7.300000

In [46]:
data.describe = data[["Battery capacity (mAh)","Screen size (inches)","Touchscreen"]].describe()
print("describe")
print(data.describe)

describe
       Battery capacity (mAh)  Screen size (inches)
count             1359.000000           1359.000000
mean              2938.489330              5.291310
std                873.514133              0.671357
min               1010.000000              2.400000
25%               2300.000000              5.000000
50%               3000.000000              5.200000
75%               3500.000000              5.700000
max               6000.000000              7.300000

In [47]:
data.sort_values(by="Battery capacity (mAh)")

,Unnamed: 0,Name,Brand,Model,Battery capacity (mAh),Screen size (inches),Touchscreen,Resolution x,Resolution y,Processor,...,Rear camera,Front camera,Operating system,Wi-Fi,Bluetooth,GPS,Number of SIMs,3G,4G/ LTE,Price
443,443,Nokia Asha 502,Nokia,Asha 502,1010,3.00,Yes,240,320,1,...,5.0,0.0,Cyanogen,Yes,Yes,No,2,No,No,3499
908,908,Samsung Z4,Samsung,Z4,1050,4.50,Yes,480,800,4,...,5.0,5.0,Tizen,Yes,Yes,Yes,2,Yes,Yes,4790
585,585,Samsung Galaxy Pocket,Samsung,Galaxy Pocket,1200,2.80,Yes,240,320,1,...,2.0,0.0,Android,Yes,Yes,Yes,1,Yes,No,3190
1166,1166,Lava A52,Lava,A52,1200,4.00,Yes,480,800,2,...,2.0,0.3,Android,Yes,Yes,Yes,2,Yes,No,1999
587,587,Nokia Asha 501,Nokia,Asha 501,1200,3.00,Yes,240,320,1,...,3.2,0.0,Cyanogen,Yes,Yes,No,2,No,No,4999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
358,358,Lenovo P2,Lenovo,P2,5100,5.50,Yes,1080,1920,8,...,13.0,5.0,Android,Yes,Yes,Yes,2,Yes,Yes,16999
157,157,Xiaomi Mi Max 2,Xiaomi,Mi Max 2,5300,6.44,Yes,1080,1920,8,...,12.0,5.0,Android,Yes,Yes,Yes,2,Yes,Yes,8999
621,621,Tecno Spark Power,Tecno,Spark Power,6000,6.35,Yes,720,1548,8,...,13.0,13.0,Android,Yes,Yes,No,2,Yes,Yes,8499
8,8,Asus ROG Phone 2,Asus,ROG Phone 2,6000,6.59,Yes,1080,2340,8,...,48.0,24.0,Android,Yes,Yes,Yes,1,Yes,Yes,37999
78,78,Samsung Galaxy M30s,Samsung,Galaxy M30s,6000,6.40,Yes,1080,2340,8,...,48.0,16.0,Android,Yes,Yes,Yes,2,Yes,Yes,12999

In [48]:
# we cant find out corr in this laibrary beacuse 2 of them is in string
selected_columns = ["Battery capacity (mAh)","Screen size (inches)"]
correlation_matrix = data[selected_columns].corr()
print(correlation_matrix)

                        Battery capacity (mAh)  Screen size (inches)
Battery capacity (mAh)                1.000000              0.746886
Screen size (inches)                  0.746886              1.000000